services:
  mysql:
    image: mysql:8.0
    container_name: chichi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PWD}" ]
      interval: 10s
      timeout: 2s
      retries: 2
    networks:
      - chichi-network

  redis:
    image: redis:alpine
    container_name: chichi-redis
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 2s
        retries: 2
    networks:
      - chichi-network

  chichi-site:
    image: ${DOCKERHUB_USERNAME}/chichi-app:latest
    container_name: chichi-site
    depends_on:
      mysql:
          condition: service_healthy
      redis:
          condition: service_healthy
    env_file:
      - .env
    networks:
      - chichi-network

  chichi-bot:
    build:
      context: ./chichi-bot
      dockerfile: Dockerfile
    container_name: chichi-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - chichi-network

  nginx:
    image: nginx:alpine
    container_name: chichi-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chichi-site
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 2s
    networks:
      - chichi-network

networks:
  chichi-network:

volumes:
  redis_data:
